# docker-compose.yaml
version: "3"

networks:
  mongo-network:
    driver: bridge

services:
  # Config Servers
  config-server-mongo-1:
    container_name: config-server-mongo-1
    image: mongo:4.0.5
    command: mongod --configsvr --replSet config-server-mongo --port 27017 --dbpath /data/db
    ports:
      - 50020:27017
    volumes:
      - config-server-mongo-1:/data/db
    networks:
      - mongo-network

  config-server-mongo-2:
    container_name: config-server-mongo-2
    image: mongo:4.0.5
    command: mongod --configsvr --replSet config-server-mongo --port 27017 --dbpath /data/db
    ports:
      - 50021:27017
    volumes:
      - config-server-mongo-2:/data/db
    networks:
      - mongo-network

  config-server-mongo-3:
    container_name: config-server-mongo-3
    image: mongo:4.0.5
    command: mongod --configsvr --replSet config-server-mongo --port 27017 --dbpath /data/db
    ports:
      - 50022:27017
    volumes:
      - config-server-mongo-3:/data/db
    networks:
      - mongo-network

  # Premier Shard
  shard-server-mongo-1:
    container_name: shard-server-mongo-1
    image: mongo:4.0.5
    command: mongod --shardsvr --replSet shard-server-mongo --port 27017 --dbpath /data/db
    ports:
      - 50001:27017
    volumes:
      - shard-server-mongo-1:/data/db
    networks:
      - mongo-network

  shard-server-mongo-2:
    container_name: shard-server-mongo-2
    image: mongo:4.0.5
    command: mongod --shardsvr --replSet shard-server-mongo --port 27017 --dbpath /data/db
    ports:
      - 50002:27017
    volumes:
      - shard-server-mongo-2:/data/db
    networks:
      - mongo-network

  shard-server-mongo-3:
    container_name: shard-server-mongo-3
    image: mongo:4.0.5
    command: mongod --shardsvr --replSet shard-server-mongo --port 27017 --dbpath /data/db
    ports:
      - 50003:27017
    volumes:
      - shard-server-mongo-3:/data/db
    networks:
      - mongo-network

  # Deuxième Shard
  shard2-server-mongo-1:
    container_name: shard2-server-mongo-1
    image: mongo:4.0.5
    command: mongod --shardsvr --replSet shard2-server-mongo --port 27017 --dbpath /data/db
    ports:
      - 50004:27017
    volumes:
      - shard2-server-mongo-1:/data/db
    networks:
      - mongo-network

  shard2-server-mongo-2:
    container_name: shard2-server-mongo-2
    image: mongo:4.0.5
    command: mongod --shardsvr --replSet shard2-server-mongo --port 27017 --dbpath /data/db
    ports:
      - 50005:27017
    volumes:
      - shard2-server-mongo-2:/data/db
    networks:
      - mongo-network

  shard2-server-mongo-3:
    container_name: shard2-server-mongo-3
    image: mongo:4.0.5
    command: mongod --shardsvr --replSet shard2-server-mongo --port 27017 --dbpath /data/db
    ports:
      - 50006:27017
    volumes:
      - shard2-server-mongo-3:/data/db
    networks:
      - mongo-network

  # 3éme Shard
  shard3-server-mongo-1:
    container_name: shard3-server-mongo-1
    image: mongo:4.0.5
    command: mongod --shardsvr --replSet shard3-server-mongo --port 27017 --dbpath /data/db
    ports:
      - 50007:27017
    volumes:
      - shard3-server-mongo-1:/data/db
    networks:
      - mongo-network

  shard3-server-mongo-2:
    container_name: shard3-server-mongo-2
    image: mongo:4.0.5
    command: mongod --shardsvr --replSet shard3-server-mongo --port 27017 --dbpath /data/db
    ports:
      - 50008:27017
    volumes:
      - shard3-server-mongo-2:/data/db
    networks:
      - mongo-network

  shard3-server-mongo-3:
    container_name: shard3-server-mongo-3
    image: mongo:4.0.5
    command: mongod --shardsvr --replSet shard3-server-mongo --port 27017 --dbpath /data/db
    ports:
      - 50009:27017
    volumes:
      - shard3-server-mongo-3:/data/db
    networks:
      - mongo-network
  # Router (mongos)
  mongos:
    container_name: mongos
    image: mongo:4.0.5
    command: mongos --configdb config-server-mongo/config-server-mongo-1:27017,config-server-mongo-2:27017,config-server-mongo-3:27017 --bind_ip_all
    ports:
      - 50000:27017
    networks:
      - mongo-network
    depends_on:
      - config-server-mongo-1
      - config-server-mongo-2
      - config-server-mongo-3

volumes:
  config-server-mongo-1:
  config-server-mongo-2:
  config-server-mongo-3:
  shard-server-mongo-1:
  shard-server-mongo-2:
  shard-server-mongo-3:
  shard2-server-mongo-1:
  shard2-server-mongo-2:
  shard2-server-mongo-3:
  shard3-server-mongo-1:
  shard3-server-mongo-2:
  shard3-server-mongo-3: